### ISSUE TITLE
Many warnings

### ISSUE THREAD

**Issue by matheusrocha89** [scup/atellier#26]
I have a project with a lot of react components so I put the attelier to make a demo of all components. But after I put the attelier the appears a lot of warning messages:
![image](https://cloud.githubusercontent.com/assets/3718366/13763463/25fb8e4a-ea25-11e5-88d3-478f0dee900f.png)

I think the bundle file of attelier have a react inside so since my project have react too there is a conflict, anybody already pass through this and find an elegant solution?

**Comment by Neablis** [comment]
This bug is caused by the bug i already filled a issue for. They use React instead of react so the two names conflict. On a non case sensitive file system you get warnings. On a case sensitive filesystem it will break.

They are working on a fix, but its a pretty easy fix so should be soon. 

https://github.com/scup/atellier/issues/17

**Comment by agutoli** [comment]
hi @matheusrocha89 and @Neablis, we just released a version v0.1.9 with this fix. tks!
